name: Compile Sketch

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create secrets
        run: |
            cp ./WetterViz/secrets_example.h ./WetterViz/secrets.h
        shell: bash

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp8266:esp8266:d1_mini_lite:xtal=80,vt=flash,exception=legacy,ssl=all,eesz=1M64,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=921600
          platforms: |
            - source-url: "http://arduino.esp8266.com/stable/package_esp8266com_index.json"
              name: "esp8266:esp8266"
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the 'fqbn' input.
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - ./WetterViz/
          libraries: |
            # The "blink" sketch being compiled in this demo doesn't use any libraries, so just use an empty list
            - name: Blynk
            - name: ArduinoJson
            - name: FastLED
